name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew

      - name: Setup android sdk
        uses: malinskiy/action-android/install-sdk@release/0.1.4

      - name: Update sdkmanager
        run: sdkmanager platform-tools

      - name: Run tests
        run: ./gradlew app:illusionDeviceDebugAndroidTest
